"""add fix_attempts to test_runs

Revision ID: 4bcd4b30e0f2
Revises: 375e677c5f22
Create Date: 2026-09-10 11:37:16.213828

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4bcd4b30e0f2'
down_revision: str | Sequence[str] | None = '375e677c5f22'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate always proposes dropping ix_code_chunks_embedding_hnsw
    # here too -- it isn't declared on the SQLAlchemy model, only created via
    # raw SQL in the Milestone 3 migration, so every autogenerate since then
    # flags it as "removed". Stripped from both upgrade() and downgrade(), as
    # every migration since has done.
    #
    # server_default (rather than a bare NOT NULL) so this doesn't fail if
    # this migration is ever applied against a test_runs table that already
    # has rows -- the model itself only needs the Python-side default=0 for
    # new rows going forward.
    op.add_column(
        'test_runs',
        sa.Column('fix_attempts', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_runs', 'fix_attempts')
    # ### end Alembic commands ###
