"""add code_changes table

Revision ID: 647d839fa986
Revises: bfff6936302e
Create Date: 2026-09-10 15:46:54.481924

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "647d839fa986"
down_revision: str | Sequence[str] | None = "bfff6936302e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "code_changes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column("generation_status", sa.String(), nullable=False),
        sa.Column("generation_error", sa.String(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("diff", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_code_changes_issue_id"), "code_changes", ["issue_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_code_changes_issue_id"), table_name="code_changes")
    op.drop_table("code_changes")
    # ### end Alembic commands ###
