"""add reviews table

Revision ID: a765d126fb9e
Revises: 4bcd4b30e0f2
Create Date: 2026-09-10 12:05:01.557370

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a765d126fb9e'
down_revision: str | Sequence[str] | None = '4bcd4b30e0f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate always proposes dropping ix_code_chunks_embedding_hnsw
    # here too -- it isn't declared on the SQLAlchemy model, only created via
    # raw SQL in the Milestone 3 migration, so every autogenerate since then
    # flags it as "removed". Stripped from both upgrade() and downgrade(), as
    # every migration since has done.
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code_change_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('comments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column(
        'created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.ForeignKeyConstraint(['code_change_id'], ['code_changes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_code_change_id'), 'reviews', ['code_change_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_code_change_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
