"""add code_chunks table and repository indexing fields

Revision ID: bb65d684cbaf
Revises: ea9dccf7fa21
Create Date: 2026-09-09 09:45:39.322587

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb65d684cbaf"
down_revision: str | Sequence[str] | None = "ea9dccf7fa21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "code_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("chunk_type", sa.String(), nullable=False),
        sa.Column("symbol_name", sa.String(), nullable=True),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_code_chunks_file_path"), "code_chunks", ["file_path"], unique=False)
    op.create_index(
        op.f("ix_code_chunks_repository_id"), "code_chunks", ["repository_id"], unique=False
    )
    op.add_column("repositories", sa.Column("indexing_error", sa.String(), nullable=True))
    op.add_column(
        "repositories", sa.Column("file_count", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "repositories", sa.Column("chunk_count", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column("repositories", sa.Column("indexed_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    # HNSW index for cosine-similarity search over embeddings. Not expressed
    # declaratively on the model (pgvector's SQLAlchemy Index mapping is
    # version-sensitive); this migration is the source of truth for it.
    op.execute(
        "CREATE INDEX ix_code_chunks_embedding_hnsw ON code_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_code_chunks_embedding_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repositories", "indexed_at")
    op.drop_column("repositories", "chunk_count")
    op.drop_column("repositories", "file_count")
    op.drop_column("repositories", "indexing_error")
    op.drop_index(op.f("ix_code_chunks_repository_id"), table_name="code_chunks")
    op.drop_index(op.f("ix_code_chunks_file_path"), table_name="code_chunks")
    op.drop_table("code_chunks")
    # ### end Alembic commands ###
