"""add issues and plans tables

Revision ID: bfff6936302e
Revises: bb65d684cbaf
Create Date: 2026-09-10 13:26:42.876346

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfff6936302e"
down_revision: str | Sequence[str] | None = "bb65d684cbaf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issues",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("planning_status", sa.String(), nullable=False),
        sa.Column("planning_error", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_issues_created_by_id"), "issues", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_issues_repository_id"), "issues", ["repository_id"], unique=False)
    op.create_table(
        "plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("relevant_files", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("implementation_steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "tests_to_add_or_change", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("risks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plans_issue_id"), "plans", ["issue_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_plans_issue_id"), table_name="plans")
    op.drop_table("plans")
    op.drop_index(op.f("ix_issues_repository_id"), table_name="issues")
    op.drop_index(op.f("ix_issues_created_by_id"), table_name="issues")
    op.drop_table("issues")
    # ### end Alembic commands ###
