"""add usage_records table

Revision ID: d77042e781ab
Revises: e75703123d8c
Create Date: 2026-09-10 12:44:31.017006

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd77042e781ab'
down_revision: str | Sequence[str] | None = 'e75703123d8c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate always proposes dropping ix_code_chunks_embedding_hnsw
    # here too -- it isn't declared on the SQLAlchemy model, only created via
    # raw SQL in the Milestone 3 migration, so every autogenerate since then
    # flags it as "removed". Stripped from both upgrade() and downgrade(), as
    # every migration since has done.
    op.create_table('usage_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=True),
    sa.Column('issue_id', sa.Uuid(), nullable=True),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column(
        'created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_issue_id'), 'usage_records', ['issue_id'], unique=False)
    op.create_index(
        op.f('ix_usage_records_repository_id'), 'usage_records', ['repository_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_repository_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_issue_id'), table_name='usage_records')
    op.drop_table('usage_records')
    # ### end Alembic commands ###
