"""add pull_requests table

Revision ID: e75703123d8c
Revises: a765d126fb9e
Create Date: 2026-09-10 12:23:01.760839

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e75703123d8c'
down_revision: str | Sequence[str] | None = 'a765d126fb9e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate always proposes dropping ix_code_chunks_embedding_hnsw
    # here too -- it isn't declared on the SQLAlchemy model, only created via
    # raw SQL in the Milestone 3 migration, so every autogenerate since then
    # flags it as "removed". Stripped from both upgrade() and downgrade(), as
    # every migration since has done.
    op.create_table('pull_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code_change_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_url', sa.String(), nullable=True),
    sa.Column(
        'created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.ForeignKeyConstraint(['code_change_id'], ['code_changes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_pull_requests_code_change_id'), 'pull_requests', ['code_change_id'], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pull_requests_code_change_id'), table_name='pull_requests')
    op.drop_table('pull_requests')
    # ### end Alembic commands ###
